### PR TITLE
Use aes128gcm encoding

### PR DESCRIPTION
**Pull request by SherClockHolmes**
Updating `webpush` to use the `aes128gcm` encoding scheme (https://github.com/SherClockHolmes/webpush-go/issues/16). Opening up this PR to track in-progress items:

  - [x] `aes128gcm` encoding
  - [x] Add example/ directory

Notable changes:
  - `httpClient` is now unexported
  - Replaced `dep` with go modules
  - Removed:
    - `aesgcm` encoding
    - Legacy GCM authentication
    - `assert` package from tests / dependencies
  - `VapidPublicKey` is now required in `Options` for VAPID
  - Moved `Urgency` logic to it's own file

### CODE REVIEW

**Comment by gbhrdt** [comment]
Thanks for the great lib. Any reason why `httpClient` is now unexported? I was using a custom transport.

**Comment by SherClockHolmes** [comment]
@gbhrdt See https://github.com/SherClockHolmes/webpush-go/issues/18 for more information. I have re-exported the interface in v1.0.1. Let me know if you run into anymore issues 😄

**Comment by gbhrdt** [comment]
@SherClockHolmes No problem, thank you for the quick update 👍 
you also removed legacy GCM Authentication. Would it be possible to re-add this as well? We have many legacy GCM subscriptions and I would have to implement this in another way.

I think https://github.com/web-push-libs/web-push also preserved this feature for backwards compatibility.

**Comment by SherClockHolmes** [comment]
@gbhrdt I believe the GCM service will be shut off by end of April 2019. My recommendation is to use the tagged version v0.0.1 or fork this repo (add back the change if you need it) until you ready to upgrade.

**Pull request merged**
